name: "Publish Word of the day"

on:
  workflow_dispatch:
  schedule:
    - cron: "50 4 * * *" # should be at ~8:10 UTC+3 (set to 7:50, github adds ~20 mins)

jobs:
  publish-word:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Install browser
        run: bunx puppeteer browsers install

      - name: Publish Word of the day
        run: bun post
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
